export const state = {
  boardId: null,
  boardName: null,
  facets: [],
  aiReasoning: true,
  items: [],
  uploading: [],
  selected: new Map(),
  bulkSelected: new Set(),
  filtersHidden: false,
  uid: 0,
  me: null,
  boards: [],
  crates: [],
  filterConfigs: [],
  selectedCrateId: null,
  showFavorites: false,
  showUntagged: false,
  sortByHearts: false,
  // semantic search: server-enabled flag, the input's draft text, the last
  // submitted query, and its results (Map id -> score; null = not searching)
  searchAvailable: false,
  searchDraft: "",
  searchQuery: "",
  searchResults: null,
  searchLoading: false,
};
